import { Book } from './book';

export const MOCK_BOOKS_EMPTY: Book[] = [];

export const MOCK_BOOKS: Book[] = [
  {
    id: 1,
    title: 'Преступление и наказание',
    author: 'Фёдор Достоевский',
    year: 1866,
    genre: 'Классика',
    rating: 4.9,
    coverUrl: 'https://picsum.photos/id/10/200/300',
  },
  {
    id: 2,
    title: 'Хоббит, или Туда и обратно',
    author: 'Дж. Р. Р. Толкин',
    year: 1937,
    genre: 'Фэнтези',
    rating: 4.8,
    coverUrl: 'https://picsum.photos/id/20/200/300',
  },
  {
    id: 3,
    title: '1984',
    author: 'Джордж Оруэлл',
    year: 1949,
    genre: 'Антиутопия',
    rating: 4.7,
  },
  {
    id: 4,
    title: 'Автостопом по галактике',
    author: 'Дуглас Адамс',
    year: 1979,
    genre: 'Научная фантастика',
    rating: 4.5,
    coverUrl: 'https://picsum.photos/id/30/200/300',
  },
  {
    id: 5,
    title: 'Мастер и Маргарита',
    author: 'Михаил Булгаков',
    year: 1967,
    genre: 'Роман',
    rating: 4.9,
  },
  {
    id: 6,
    title: 'Ведьмак: Последнее желание',
    author: 'Анджей Сапковский',
    year: 1993,
    genre: 'Фэнтези',
    rating: 4.6,
    coverUrl: 'https://picsum.photos/id/40/200/300',
  },
  {
    id: 7,
    title: 'Марсианин',
    author: 'Энди Уир',
    year: 2011,
    genre: 'Научная фантастика',
    rating: 3.4,
    coverUrl: 'https://picsum.photos/id/50/200/300',
  },
  {
    id: 8,
    title: 'Убийство в Восточном экспрессе',
    author: 'Агата Кристи',
    year: 1934,
    genre: 'Детектив',
    rating: 4.8,
  },
  {
    id: 9,
    title: 'Великий Гэтсби',
    author: 'Ф. Скотт Фицджеральд',
    year: 1925,
    genre: 'Классика',
    rating: 3.3,
    coverUrl: 'https://picsum.photos/id/60/200/300',
  },
  {
    id: 10,
    title: 'Дюна',
    author: 'Фрэнк Герберт',
    year: 1965,
    genre: 'Научная фантастика',
    rating: 4.7,
    coverUrl: 'https://picsum.photos/id/70/200/300',
  },
];
